### ISSUE TITLE
Stop using deprecated `set-output` command.

### ISSUE THREAD

**Issue by mtfoley** [mtfoley/pr-compliance-action#292]
**Is your feature request related to a problem? Please describe.**
Runs of this action now show error messages, like:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Describe the solution you'd like**
I believe we need to update to newer version of `@actions/core` NPM package. There may be more to it though.

**Describe alternatives you've considered**
N/A

**Additional context**
After any modifications to package.json or other things, command `npm run all` needs to be run locally so that dist files are updated.

**Comment by ArcadeMode** [comment]
Hello, do you have any due date on this? We're enjoying your action and are also seeing the set-output deprecation warning but also the node12 deprecation warning, perhaps these things can be upgraded together.

**Comment by mtfoley** [comment]
I don't have a specific time frame I had in mind. I think I'll free up in a week or two when I've got some time off work scheduled, so I can probably take a look then.

**Comment by mtfoley** [comment]
Also, I guess based on the article mentioned in the deprecation message, things will change in mid-2023.  Looks like the same goes for the Node v12 deprecation.
