### ISSUE TITLE
regular expression is not case sensitive although configured like this in code

### ISSUE THREAD

**Issue by shimonelbaz** [mtfoley/pr-compliance-action#325]
**Describe the bug**
when defining a regular expression for PR body, it should be case insensitive (according to this line of code: `const regex = new RegExp(regexString, 'mi')` ) , however , in actual it is case sensitive.

**To Reproduce**
1. define a workflow with the following regex: `(relat|fix|resolv|clos)(e)*(s|d)* Vorlon-inc\/etc#\d+`
2. create a PR with the following content in body: closes Vorlon-inc/etc#999 - check will pass
3. update the PR body to : closes Vorlon-Inc/etc#999 - check should pass as well but fails

**Expected behavior**
regex should be case insensitive.

**Additional context**
in general , it might be a better option to make the regex flags configurable (either by a parameter or as part of the regex itself [remove the flags from declaration and let them be part of the string i.e - `/(relat|fix|resolv|clos)(e)*(s|d)* Vorlon-inc\/etc#\d+/mi` ]

**Comment by mtfoley** [comment]
Hi @shimonelbaz thanks for filing this! I have tried to reproduce in a private repo without success so far, and I tried adding a unit test on a local branch for this but the test passes. I'll make one or two more passes at the repro but if you have a public one to point me to, that may help.

**Comment by shimonelbaz** [comment]
hey @mtfoley , we are using an org repo but it is private.
thank you for the rapid response! i will try and do it with some more specific procedure and update here.

**Comment by shimonelbaz** [comment]
Hi, 
i am closing this issue , seems like i made a mistake and the content was HTML formatted and that is why the regex did not catch it, not because of case sensitivity. the actual content was a url which of course has a different format.

**Comment by mtfoley** [comment]
Got it. Please don't hesitate to file an issue if you come across bugs or features you feel would be appropriate 😀 you may have some opinions on #311, since right now it would work differently (if at all) on private repos.
