### ISSUE TITLE
issue labels output is wrong with zero errors

### ISSUE THREAD

**Issue by mtfoley** [mtfoley/pr-compliance-action#375]
**Describe the bug**

The action output for "issue-label-check" is `false` when zero errors are found.

**Expected behavior**
Outputs for a passing check should be set to true.

**Screenshots**

**Additional context**

**Comment by mtfoley** [comment]
FYI @JoshuaKGoldberg - i missed this on the review. Probably pretty low impact because I don't think many people use the action outputs and the "checks" aspects are working correctly.

**Comment by JoshuaKGoldberg** [comment]
Err, do you have a repro link I can look at? This code looks like it should be not-buggy:

https://github.com/mtfoley/pr-compliance-action/blob/5e76f6982b6dc69630648f08556e25b4f8e93bfd/src/main.ts#L115

**Comment by mtfoley** [comment]
the checks pass fine, so that's good. `!![].length` outputs false it looks like, but we should be setting output to true if that check passes. ideally, the parts that make up the constant `prCompliant` above that are individually reflected in the outputs.  
https://github.com/mtfoley/pr-compliance-action/blob/5e76f6982b6dc69630648f08556e25b4f8e93bfd/src/main.ts#L102-L107
I'll see if i can reproduce it in a public spot, but i find that I need to re-run workflows with debug logging turned on to see the output values.

**Comment by mtfoley** [comment]
Let me know if you can see this action run for reproduction:
https://github.com/mtfoley/open-sauced/actions/runs/5993189266/job/16253392863
The other outputs read true because they were successful.
