### ISSUE TITLE
Does this works with links?

### ISSUE THREAD

**Issue by a0m0rajab** [mtfoley/pr-compliance-action#384]
**Is your feature request related to a problem? Please describe.**
I am not quite sure if this is a Feature request or a bug. but this action did not work when we had a link after the close tag 

like: close https://github.com/example/example/issues/23594

**Describe the solution you'd like**

it would be great if this is solved, or is this an issue from the action runing side?

**Describe alternatives you've considered**

**Additional context**

**Comment by a0m0rajab** [comment]
This has been discovered in ivy project: https://github.com/unifyai/ivy/pull/23594

**Comment by mtfoley** [comment]
Hi @a0m0rajab I can take a look at this feature. Meanwhile, you should be able to have direct control over what the issue reference will match using the `body-regex` input (which does not appear that it would catch URLs by default). I also noticed that you have v0.5.0 in use, and the action is at v1.3.1 at the moment.  You may want to update. For example, the `body-regex` pattern was updated in v1.2.1.
https://github.com/mtfoley/pr-compliance-action/releases

**Comment by a0m0rajab** [comment]
Thanks for that, I will update it to that, 
I did a quick check and I think this is related to the regex we have right now: 
https://github.com/mtfoley/pr-compliance-action/blob/b40d80a07ff378b69da0c4c1d7d2b4c2b638d080/action.yml#L42
